--- #YAML:1.0
name:               LWP-UserAgent-POE
version:            0.03
abstract:           Drop-in LWP::UserAgent replacement in POE environments
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:        0
    Log::Log4perl:        1
    POE:                  0.9999
    POE::Component::Client::HTTP:  0.83
resources:
    repository:  http://github.com/mschilli/lwp-useragent-poe-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
