--- #YAML:1.0
name:                LWP-UserAgent-POE
version:             0.02
abstract:            Drop-in LWP::UserAgent replacement in POE environments
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    HTTP::Request:                 0
    Log::Log4perl:                 1
    POE:                           0.9999
    POE::Component::Client::HTTP:  0.83
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
