---
abstract: 'Drop-in LWP::UserAgent replacement in POE environments'
author:
  - 'Mike Schilli <cpan@perlmeister.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-UserAgent-POE
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  Log::Log4perl: 1
  POE: 0.9999
  POE::Component::Client::HTTP: 0.83
  POE::Component::SSLify: 1.008
resources:
  repository: http://github.com/mschilli/lwp-useragent-poe-perl
version: 0.04
